/*
  STUDENT DATA
  ------------
  Your simple "student list." Add, edit, or remove a student by
  editing the STUDENTS array below — nothing else needs to change.

  Each student's portal is just their own Notion page, embedded in
  an iframe. To get a student's notionUrl:
    1. In Notion, open their page -> Share -> Publish tab -> Publish.
    2. Click "Embed this page" -> "Copy this code".
    3. That gives you a snippet with <iframe src="...">. Copy just
       the URL inside the quotes and paste it below.

  notionAvailable: set to false for a student whose Notion page
  shouldn't be embedded yet (not ready, broken, still a placeholder
  URL, etc). Their portal page will show a "temporarily unavailable"
  message with a button linking straight to notionUrl instead of the
  iframe. Flip it back to true once their page is ready to embed.

  NOT SECURE — by design: this whole file is sent to every visitor's
  browser, so usernames, passwords, and every notionUrl below are
  all technically visible to anyone who looks at the page source.
  That's fine for a local/low-stakes site (see README.md).

  One extra thing worth knowing: embedding requires each Notion page
  to be published/public, so the Notion page itself is viewable by
  anyone with that link, whether or not they ever log into this
  portal. The login here only controls which link loads on which
  portal page — it doesn't make the linked Notion page private.

  This file is regenerated by zenith-cli — hand edits survive until
  the next `zenith` command writes to it, but are safest made
  through the CLI so the format above stays consistent.
*/

// The shared class calendar — the same for every student, unlike
// notionUrl below which is each student's own page. To get this:
// in Google Calendar, go to the calendar's Settings -> "Integrate
// calendar" -> copy the "Embed code" -> paste just the URL inside
// the iframe's src="..." here.
const CALENDAR_URL = "https://calendar.google.com/calendar/embed?src=f378c5925c22121a1f448ff08358c807fce36f9997098326218425ba70498bba%40group.calendar.google.com&ctz=Asia%2FManila";

// The shared submission form — same one for every student. To embed
// a Google Form like this, take the normal viewform link and swap
// its query string for "?embedded=true".
const SUBMISSION_FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLScqPBskg9HOSPRXvaLHIudlpEpuwZKDs_UEjwxx_Dp0Ujgnpg/viewform?embedded=true";

// "Right Now" is each student's single current to-do, shown on the
// Right Now page. Two shapes:
//   state: "your-move" -> chapter, unit, instruction, due (optional)
//   state: "waiting"   -> chapter, unit, note
// Leave it off entirely for a student to show the page's empty state.

// "feedback" is each student's feedback log, shown on the Feedback
// page — a plain array of { date, chapter, unit, content }. Add new
// entries to the TOP of the array (newest first); the page just
// renders the array in order, no sorting. Leave it off entirely (or
// an empty array) for a student to show the page's empty state.
const STUDENTS = [
  {
    "username": "alice",
    "password": "alice123",
    "name": "Alice Inthe Wonderland",
    "portal": {
      "notionUrl": "https://embed.embednotion.com/39edb87002c4804c855ec1c9bbb7791d",
      "notionAvailable": false
    }
  },
  {
    "username": "bogue",
    "password": "password",
    "name": "Bogue Kwon",
    "portal": {
      "notionUrl": "https://embed.embednotion.com/39edb87002c4804c855ec1c9bbb7791d",
      "notionAvailable": true
    },
    "rightNow": {
      "state": "your-move",
      "chapter": "Chapter 1",
      "unit": "R",
      "note": "Complete reviewing chapter 1 by writing down mistakes and reflecting actively for each problem, writing down the source and why you got wrong.",
      "instruction": "Complete reviewing chapter 1 by writing down mistakes and reflecting actively for each problem, writing down the source and why you got wrong.",
      "due": "Tuesday"
    },
    "feedback": [
      {
        "date": "Jul 24",
        "chapter": "Chapter 5",
        "unit": "C",
        "content": "Strong work overall — your setup on the related rates problems was clean. Watch your sign when a rate is decreasing; a couple of answers flipped sign because of that. Worth a quick look back at #4 and #7."
      },
      {
        "date": "Jul 18",
        "chapter": "Chapter 4",
        "unit": "S",
        "content": "Good recovery after the mock — implicit differentiation is clicking now. One thing to keep an eye on: you're solving correctly but slower than you need to be on chain rule setups. Worth drilling speed here before the next T."
      },
      {
        "date": "Jul 10",
        "chapter": "Chapter 4",
        "unit": "C",
        "content": "A few of these were rushed — question 3 and 9 were misread rather than miscalculated. Try reading the question twice before writing anything down; the method was right both times."
      }
    ]
  },
  {
    "username": "hamin",
    "password": "password",
    "name": "Hamin Park",
    "portal": {
      "notionUrl": "https://your-workspace.notion.site/REPLACE-WITH-CHARLIES-PAGE",
      "notionAvailable": false
    }
  },
  {
    "username": "seohu",
    "password": "password",
    "name": "Seohu Lee",
    "portal": {
      "notionUrl": "https://wealthy-mapusaurus-5ee.notion.site/3a3db87002c48099b507ea08fa755507?v=59adb87002c482f0b8618874306037c3&pvs=73",
      "notionAvailable": false
    },
    "rightNow": {
      "state": "your-move",
      "chapter": "Chapter 1",
      "unit": "B",
      "instruction": "Read through the chapter and actively work through the examples as you go — don't just read past them. Use whatever helps you actually close the gaps. Message us once you're done.",
      "due": "undecided"
    }
  },
  {
    "username": "kyjv9981",
    "password": "password",
    "name": "Yong Joon Kim",
    "portal": {
      "notionUrl": "d",
      "notionAvailable": false
    },
    "rightNow": {
      "state": "your-move",
      "chapter": "Chapter 6",
      "unit": "B",
      "instruction": "Read through the chapter and actively work through the examples as you go — don't just read past them. Use whatever helps you actually close the gaps. Message us once you're done.",
      "due": "Friday"
    },
    "feedback": [
      {
        "date": "Jul 22",
        "chapter": "Chapter 5",
        "unit": "S",
        "content": "Nice improvement on related rates since last time. Keep working through the 발상노트 for the two problems you missed — both were domain-restriction oversights, same pattern as Chapter 4."
      },
      {
        "date": "Jul 12",
        "chapter": "Chapter 4",
        "unit": "C",
        "content": "Solid effort. Most of what you missed came down to forgetting to check the domain before finalizing an answer — worth a quick habit check before submitting next time."
      }
    ],
    "cheatSheet": [
      {
        "topic": "Domain Restrictions",
        "source": "4C-14, 5S-9",
        "pattern": "Shows up twice so far — the method is right both times, the answer just isn't checked against the original expression's domain afterward. Before finalizing, ask: does this value actually work back in the un-simplified expression, e.g. is $x=-2$ still valid if the original required $x > 0$?"
      },
      {
        "topic": "Related Rates Setup",
        "source": "5C-6",
        "pattern": "Going well — keep setting up straight from the diagram: $\\dfrac{dV}{dt} = \\dfrac{dV}{dr} \\cdot \\dfrac{dr}{dt}$ rather than re-deriving the volume formula each time. Faster and less room for a sign slip."
      }
    ]
  }
];

// Teachers are a separate list from STUDENTS — same username/password
// shape, but they log into a different dashboard (teacher.html) with
// its own layout instead of the student portal pages. Kept minimal
// for now; the actual dashboard content/structure is still TBD.
const TEACHERS = [
  {
    "username": "teacher",
    "password": "password",
    "name": "Zenith Teacher"
  }
];
