/*
  STUDENT DATA
  ------------
  Your simple "student list." Add, edit, or remove a student by
  editing the STUDENTS array below — nothing else needs to change.

  Each student's portal is just their own Notion page, embedded in
  an iframe. To get a student's notionUrl:
    1. In Notion, open their page -> Share -> Publish tab -> Publish.
    2. Click "Embed this page" -> "Copy this code".
    3. That gives you a snippet with <iframe src="...">. Copy just
       the URL inside the quotes and paste it below.

  notionAvailable: set to false for a student whose Notion page
  shouldn't be embedded yet (not ready, broken, still a placeholder
  URL, etc). Their portal page will show a "temporarily unavailable"
  message with a button linking straight to notionUrl instead of the
  iframe. Flip it back to true once their page is ready to embed.

  NOT SECURE — by design: this whole file is sent to every visitor's
  browser, so usernames, passwords, and every notionUrl below are
  all technically visible to anyone who looks at the page source.
  That's fine for a local/low-stakes site (see README.md).

  One extra thing worth knowing: embedding requires each Notion page
  to be published/public, so the Notion page itself is viewable by
  anyone with that link, whether or not they ever log into this
  portal. The login here only controls which link loads on which
  portal page — it doesn't make the linked Notion page private.

  This file is regenerated by zenith-cli — hand edits survive until
  the next `zenith` command writes to it, but are safest made
  through the CLI so the format above stays consistent.
*/

// The shared class calendar — the same for every student, unlike
// notionUrl below which is each student's own page. To get this:
// in Google Calendar, go to the calendar's Settings -> "Integrate
// calendar" -> copy the "Embed code" -> paste just the URL inside
// the iframe's src="..." here.
const CALENDAR_URL = "https://calendar.google.com/calendar/embed?src=f378c5925c22121a1f448ff08358c807fce36f9997098326218425ba70498bba%40group.calendar.google.com&ctz=Asia%2FManila";

// The shared submission form — same one for every student. To embed
// a Google Form like this, take the normal viewform link and swap
// its query string for "?embedded=true".
const SUBMISSION_FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLScqPBskg9HOSPRXvaLHIudlpEpuwZKDs_UEjwxx_Dp0Ujgnpg/viewform?embedded=true";

// "Right Now" is each student's single current to-do, shown on the
// Right Now page. Two shapes:
//   state: "your-move" -> chapter, unit, instruction, due (optional)
//   state: "waiting"   -> chapter, unit, note
// Leave it off entirely for a student to show the page's empty state.

// "feedback" is each student's feedback log, shown on the Feedback
// page — a plain array of { date, chapter, unit, content }. Add new
// entries to the TOP of the array (newest first); the page just
// renders the array in order, no sorting. Leave it off entirely (or
// an empty array) for a student to show the page's empty state.
const STUDENTS = [
  {
    "username": "alice",
    "password": "alice123",
    "name": "Alice Inthe Wonderland",
    "portal": {
      "notionUrl": "https://embed.embednotion.com/39edb87002c4804c855ec1c9bbb7791d",
      "notionAvailable": false
    }
  },
  {
    "username": "bogue",
    "password": "password",
    "name": "Bogue Kwon",
    "portal": {
      "notionUrl": "https://wealthy-mapusaurus-5ee.notion.site/3aadb87002c48017b10cd3db81e407f6?v=6e4db87002c48266bdf508f048d0fa9e&source=copy_link",
      "notionAvailable": false 
    },
    "rightNow": {
      "state": "your-move",
      "chapter": "Chapter 1",
      "unit": "R",
      "note": "Complete reviewing chapter 1 by writing down mistakes and reflecting actively for each problem, writing down the source and why you got wrong.",
      "instruction": "Complete reviewing chapter 1 by writing down mistakes and reflecting actively for each problem, writing down the source and why you got wrong.",
      "due": "Tuesday"
    },
    "feedback": [
      {
        "date": "Jul 24",
        "chapter": "Chapter 5",
        "unit": "C",
        "content": "Strong work overall — your setup on the related rates problems was clean. Watch your sign when a rate is decreasing; a couple of answers flipped sign because of that. Worth a quick look back at #4 and #7."
      },
      {
        "date": "Jul 18",
        "chapter": "Chapter 4",
        "unit": "S",
        "content": "Good recovery after the mock — implicit differentiation is clicking now. One thing to keep an eye on: you're solving correctly but slower than you need to be on chain rule setups. Worth drilling speed here before the next T."
      },
      {
        "date": "Jul 10",
        "chapter": "Chapter 4",
        "unit": "C",
        "content": "A few of these were rushed — question 3 and 9 were misread rather than miscalculated. Try reading the question twice before writing anything down; the method was right both times."
      }
    ],
    "roadmap": [
      { "name": "AP Calculus BC Exam Booklet", "category": "I-information", "chapter": "Chapter 0", "status": "Complete", "url": "https://drive.google.com/file/d/1Zm7BzijHtGZOmttmyEjfNXPvUe-o_il7/view?usp=drive_link" },
      { "name": "AP Calculus Exam Meta Information", "category": "I-information", "chapter": "Chapter 0", "status": "Complete", "url": "https://drive.google.com/file/d/1ZQ_sPhP3ZTm9BBAlWH713yreCzF7ci-m/view?usp=drive_link" },
      { "name": "B1-Functions", "category": "B-book chapter", "chapter": "Chapter 1", "status": "Review", "url": "https://drive.google.com/file/d/1JKFuYfSijODTUWMusFJS70BRhqNuvUQa/view?usp=drive_link" },
      { "name": "C1-Functions Problems", "category": "C-coursework", "chapter": "Chapter 1", "status": "Review", "url": "https://drive.google.com/file/d/1srrUF6c_0cXnEdLiaD9Le05iWw7_kCXJ/view?usp=drive_link" },
      { "name": "S1-Functions Solutions", "category": "S-solution manual", "chapter": "Chapter 1", "status": "Unlocked", "url": "https://drive.google.com/file/d/1DPo60sEJWR7Byl70U1pOHBTQaBFw5Ey8/view?usp=drive_link" },
      { "name": "R1-Functions Review", "category": "R-Review", "chapter": "Chapter 1", "status": "Review" },
      { "name": "T1-Functions Test", "category": "T-Test", "chapter": "Chapter 1", "status": "Locked" },
      { "name": "B2-Limits and Continuity", "category": "B-book chapter", "chapter": "Chapter 2", "status": "Unlocked", "url": "https://drive.google.com/file/d/1xDn8xrsDdYVlDl5l4hLWlVzWUkEe7Bs9/view?usp=drive_link" },
      { "name": "C2-Limits and Continuity Problems", "category": "C-coursework", "chapter": "Chapter 2", "status": "Unlocked", "url": "https://drive.google.com/file/d/1_o35NK356pUnoAIAfQZang5vgH3AMOQP/view?usp=drive_link" },
      { "name": "S2-Limits and Continuity Solutions", "category": "S-solution manual", "chapter": "Chapter 2", "status": "Locked", "url": "https://drive.google.com/file/d/17pzhOM1QGu8z-zm3YovNEe40ECpexSaF/view?usp=drive_link" },
      { "name": "R2-Functions Review", "category": "R-Review", "chapter": "Chapter 2", "status": "Locked" },
      { "name": "T2-Functions Test", "category": "T-Test", "chapter": "Chapter 2", "status": "Locked" },
      { "name": "B3-Differentiation", "category": "B-book chapter", "chapter": "Chapter 3", "status": "Optional-Reading", "url": "https://drive.google.com/file/d/1Pmtx_jKUGFLyOQhlFoYmI73UaW0AVEp7/view?usp=drive_link" },
      { "name": "C3-Differentiation Problems", "category": "C-coursework", "chapter": "Chapter 3", "status": "Optional-Reading", "url": "https://drive.google.com/file/d/19NGG8CUv7LhzRoVS6q7kx_pGaBkeHQL_/view?usp=drive_link" },
      { "name": "S3-Differentiation Solutions", "category": "S-solution manual", "chapter": "Chapter 3", "status": "Locked", "url": "https://drive.google.com/file/d/1EolTf6Fc9d4kROvX_-h_kdgXVhQCINZD/view?usp=drive_link" },
      { "name": "R3-Differentiation Review", "category": "R-Review", "chapter": "Chapter 3", "status": "Locked" },
      { "name": "T3-Differentiation Test", "category": "T-Test", "chapter": "Chapter 3", "status": "Locked" },
      { "name": "B4-Application of Differential Calculus", "category": "B-book chapter", "chapter": "Chapter 4", "status": "Locked", "url": "https://drive.google.com/file/d/176JaK2_fIDJKMu4r5lswHf55VDoHb1Yh/view?usp=drive_link" },
      { "name": "C4-Application of Differential Calculus Problems", "category": "C-coursework", "chapter": "Chapter 4", "status": "Locked", "url": "https://drive.google.com/file/d/1nEcmDBxr7c4SnXnzoqVC8xWJULMjKv1V/view?usp=drive_link" },
      { "name": "S4-Application of Differential Calculus Solutions", "category": "S-solution manual", "chapter": "Chapter 4", "status": "Locked", "url": "https://drive.google.com/file/d/1s6gS0JXb7Qkv4bcuScdMHolZpQzwZA3o/view?usp=drive_link" },
      { "name": "R4-Application of Differential Calculus Review", "category": "R-Review", "chapter": "Chapter 4", "status": "Locked" },
      { "name": "T4-Application of Differential Calculus Test", "category": "T-Test", "chapter": "Chapter 4", "status": "Locked" },
      { "name": "B5-Antidifferentiation", "category": "B-book chapter", "chapter": "Chapter 5", "status": "Locked", "url": "https://drive.google.com/file/d/1bt6G1c_qpNHzB8sk-JI2t-Vc1kaG333K/view?usp=drive_link" },
      { "name": "C5-Antidifferentiation Problems", "category": "C-coursework", "chapter": "Chapter 5", "status": "Locked", "url": "https://drive.google.com/file/d/1vNyQOAqiXgRB1yfvsxw7E5lhAxALJ8UB/view?usp=drive_link" },
      { "name": "S5-Antidifferentiation Solutions", "category": "S-solution manual", "chapter": "Chapter 5", "status": "Locked", "url": "https://drive.google.com/file/d/1dGO0xQYAWr9ial7bo62ATko0e1V9npbo/view?usp=drive_link" },
      { "name": "R5-Antidifferentiation Review", "category": "R-Review", "chapter": "Chapter 5", "status": "Locked" },
      { "name": "T5-Antidifferentiation Test", "category": "T-Test", "chapter": "Chapter 5", "status": "Locked" },
      { "name": "B6-Definite Integrals", "category": "B-book chapter", "chapter": "Chapter 6", "status": "Locked", "url": "https://drive.google.com/file/d/1zDSFHj-udXu9Qy0nrN-B8VbWRD0KmIUt/view?usp=drive_link" },
      { "name": "C6-Definite Integrals Problems", "category": "C-coursework", "chapter": "Chapter 6", "status": "Locked", "url": "https://drive.google.com/file/d/1MN9WDjoFhj29pTPRd622yPdGLKQFXsld/view?usp=drive_link" },
      { "name": "S6-Definite Integrals Solutions", "category": "S-solution manual", "chapter": "Chapter 6", "status": "Locked", "url": "https://drive.google.com/file/d/1pML1Se9S-xH4bS1TFBp3UpNSyYuqQwla/view?usp=drive_link" },
      { "name": "R6-Definite Integrals Review", "category": "R-Review", "chapter": "Chapter 6", "status": "Locked" },
      { "name": "T6-Definite Integrals Test", "category": "T-Test", "chapter": "Chapter 6", "status": "Locked" },
      { "name": "B7-Application of Integration to Geometry", "category": "B-book chapter", "chapter": "Chapter 7", "status": "Locked", "url": "https://drive.google.com/file/d/1qzq9nH9S1AKKy8maEp5tKug1sUXHBQyN/view?usp=drive_link" },
      { "name": "C7-Application of Integration to Geometry Problems", "category": "C-coursework", "chapter": "Chapter 7", "status": "Locked", "url": "https://drive.google.com/file/d/1XyXk_UTTlm4rx0PVT4fZz7VdWlNSpUcA/view?usp=drive_link" },
      { "name": "S7-Application of Integration to Geometry Solutions", "category": "S-solution manual", "chapter": "Chapter 7", "status": "Locked", "url": "https://drive.google.com/file/d/1JDNnEy-gksUoVmF-XCG1aH3_YeYqhGU5/view?usp=drive_link" },
      { "name": "R7-Application of Integration to Geometry Review", "category": "R-Review", "chapter": "Chapter 7", "status": "Locked" },
      { "name": "T7-Application of Integration to Geometry Test", "category": "T-Test", "chapter": "Chapter 7", "status": "Locked" },
      { "name": "B8-Further Applications of Integration", "category": "B-book chapter", "chapter": "Chapter 8", "status": "Locked", "url": "https://drive.google.com/file/d/1AjmoXuebty9WbTfmKgKB_EYCFP58aJWO/view?usp=drive_link" },
      { "name": "C8-Further Application of Integration Problems", "category": "C-coursework", "chapter": "Chapter 8", "status": "Locked", "url": "https://drive.google.com/file/d/1bQrM0wkcrnj0A3uIUD5NhtM5BV1CUd7i/view?usp=drive_link" },
      { "name": "S8-Further Application of Integration Solutions", "category": "S-solution manual", "chapter": "Chapter 8", "status": "Locked", "url": "https://drive.google.com/file/d/1OV_9DvjrlOeVzup-RpgobnQfMLXXn4TR/view?usp=drive_link" },
      { "name": "R8-Further Application of Integration Review", "category": "R-Review", "chapter": "Chapter 8", "status": "Locked" },
      { "name": "T8-Further Application of Integration Test", "category": "T-Test", "chapter": "Chapter 8", "status": "Locked" },
      { "name": "B9-Differential Equations", "category": "B-book chapter", "chapter": "Chapter 9", "status": "Locked", "url": "https://drive.google.com/file/d/1eW1C11UZUfhdYyEqu-yOHIh4hn_46qvA/view?usp=drive_link" },
      { "name": "C9-Differential Equations Problems", "category": "C-coursework", "chapter": "Chapter 9", "status": "Locked", "url": "https://drive.google.com/file/d/14AVNzubvCBozVWwd_UwLKAzXVqwjz0L1/view?usp=drive_link" },
      { "name": "S9-Differential Equations Solutions", "category": "S-solution manual", "chapter": "Chapter 9", "status": "Locked", "url": "https://drive.google.com/file/d/1dyBogdVu21CpfiaCyUqViZ2fVcJn01zf/view?usp=drive_link" },
      { "name": "R9-Differential Equations Review", "category": "R-Review", "chapter": "Chapter 9", "status": "Locked" },
      { "name": "T9-Differential Equations Test", "category": "T-Test", "chapter": "Chapter 9", "status": "Locked" },
      { "name": "B10-Sequences and Series", "category": "B-book chapter", "chapter": "Chapter 10", "status": "Locked", "url": "https://drive.google.com/file/d/1On07-Pxn3yhw9rqqy2UzHL_HXguwHL6H/view?usp=drive_link" },
      { "name": "C10-Sequences and Series Problems", "category": "C-coursework", "chapter": "Chapter 10", "status": "Locked", "url": "https://drive.google.com/file/d/12lbYSKyWNW1Ab100P6_wWOnWKfRVuWpm/view?usp=drive_link" },
      { "name": "S10-Sequences and Series Solutions", "category": "S-solution manual", "chapter": "Chapter 10", "status": "Locked", "url": "https://drive.google.com/file/d/1qSZ-foEm_3_UGJDIj68J5-9wvH1Ea7ga/view?usp=drive_link" },
      { "name": "R10-Sequences and Series Review", "category": "R-Review", "chapter": "Chapter 10", "status": "Locked" },
      { "name": "T10-Sequences and Series Test", "category": "T-Test", "chapter": "Chapter 10", "status": "Locked" },
      { "name": "C11-Miscellaneous Multiple Choice Questions", "category": "C-coursework", "chapter": "Chapter 11", "status": "Locked", "url": "https://drive.google.com/file/d/1LIgCn4eavP3B2Ne-gGbnKx_qr3XxT9-i/view?usp=drive_link" },
      { "name": "S11-Miscellaneous Multiple Choice Questions Solutions", "category": "S-solution manual", "chapter": "Chapter 11", "status": "Locked", "url": "https://drive.google.com/file/d/18CRylj_a4Ocnf1Yk46PQomBaI2Co84h-/view?usp=drive_link" },
      { "name": "R11-Miscellaneous Multiple Choice Questions Review", "category": "R-Review", "chapter": "Chapter 11", "status": "Locked" },
      { "name": "C12-Miscellaneous Free Response Questions", "category": "C-coursework", "chapter": "Chapter 12", "status": "Locked", "url": "https://drive.google.com/file/d/1HrGReb5uEZz-1WugOYJ8PuOrbuyRso3F/view?usp=drive_link" },
      { "name": "S12-Miscellaneous Free Response Questions Solutions", "category": "S-solution manual", "chapter": "Chapter 12", "status": "Locked", "url": "https://drive.google.com/file/d/1rBXVa-9OfhdPeUCI7d_FHJKNRn2j4nrM/view?usp=drive_link" },
      { "name": "R12-Miscellaneous Free Response Questions Review", "category": "R-Review", "chapter": "Chapter 12", "status": "Locked" },
      { "name": "M1-Full Mock Test 1", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1tAhprt5xldGpONJlyAbeRicCrrgkAZdM/view?usp=drive_link" },
      { "name": "M1S-Full Mock Test 1 Solution", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1RBhkIDr8DKTJzRmGeEc9BrUTEv1UiTSy/view?usp=drive_link" },
      { "name": "M1R-Full Mock Test 1 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M2-Full Mock Test 2", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1U8c-vo8NzxvI_0x_Aw2LQQy3WXybmC6i/view?usp=drive_link" },
      { "name": "M2S-Full Mock Test 2 Solution", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1S_Bb_j6w2kPY4__UpEchcJkl9vkznldS/view?usp=drive_link" },
      { "name": "M2R-Full Mock Test 2 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M3-Full Mock Test 3", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1gL7bJ4yffCR2EZ2wNOe3TnEJo_MjiHum/view?usp=drive_link" },
      { "name": "M3S-Full Mock Test 3 Solution", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1IFWIPap_A-xm6LGGtP3QqT_bV69nHk7_/view?usp=drive_link" },
      { "name": "M3R-Full Mock Test 3 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M4-FRQ Mock 4", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1IDfZvY8lVcCUwqbYCjTu32cVqdDXVaf4/view?usp=drive_link" },
      { "name": "M4S-FRQ Mock 4 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1PVw15uOPBzefCLjEZXZ5f_OqVxFOXU2W/view?usp=drive_link" },
      { "name": "M4R-FRQ Mock 4 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M5-FRQ Mock 5", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/13um9F8xTM-NGdsNghkEvv3_KrspUjLHk/view?usp=drive_link" },
      { "name": "M5S-FRQ Mock 5 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1HZi_LvVrumTfe3VKaQelGssmyFwfiiuC/view?usp=drive_link" },
      { "name": "M5R-FRQ Mock 5 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M6-FRQ Mock 6", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1vQeyfNHgOMp8quhft1mTcPq4XSlb52RD/view?usp=drive_link" },
      { "name": "M6S-FRQ Mock 6 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/15DuEPBbg04fDeS8PUMaCRsFHfC1EzEfc/view?usp=drive_link" },
      { "name": "M6R-FRQ Mock 6 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M7-FRQ Mock 7", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1_LkWfuAsZUOYvANxiVYdXIa7bULO7Yzh/view?usp=drive_link" },
      { "name": "M7S-FRQ Mock 7 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1vj-VgWY-wT00RkdY4wUbHPh7XJ_MtyNk/view?usp=drive_link" },
      { "name": "M8R-FRQ Mock 7 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M8-FRQ Mock 8", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1KqvLYIis_8feMVS1zDixS6PPZjBxtXHd/view?usp=drive_link" },
      { "name": "M8S-FRQ Mock 8 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1eG9Ksj6Af8t6PGX7R_T3knVLgsCg8e38/view?usp=drive_link" },
      { "name": "M8R-FRQ Mock 8 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M9-FRQ Mock 9", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1E1rDrUFeh2311Gzg3ln3eR5Bsu1yJZeQ/view?usp=drive_link" },
      { "name": "M9S-FRQ Mock 9 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1hh-sZH8uxDsR0V8O3nhjJ_BkFvfuQ3Ap/view?usp=drive_link" },
      { "name": "M9R-FRQ Mock 9 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M10-FRQ Mock 10", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1AZPOd1iaPTA8JJJmlooee7Ym1D9Jq79H/view?usp=drive_link" },
      { "name": "M10S-FRQ Mock 10 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1V36m1RowaKnVLvcEb7dxJEFWGpsp3DFJ/view?usp=drive_link" },
      { "name": "M10R-FRQ Mock 10 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" }
    ]
  },
  {
    "username": "hamin",
    "password": "password",
    "name": "Hamin Park",
    "portal": {
      "notionUrl": "https://your-workspace.notion.site/REPLACE-WITH-CHARLIES-PAGE",
      "notionAvailable": false
    }
  },
  {
    "username": "seohu",
    "password": "password",
    "name": "Seohu Lee",
    "portal": {
      "notionUrl": "https://wealthy-mapusaurus-5ee.notion.site/3aadb87002c48013b4cdddec5d117b8b?v=e11db87002c483669cfb08aae95fc5ab&source=copy_link",
      "notionAvailable": false
    },
    "rightNow": {
      "state": "your-move",
      "chapter": "Chapter 1",
      "unit": "B",
      "instruction": "Read through the chapter and actively work through the examples as you go — don't just read past them. Use whatever helps you actually close the gaps. Message us once you're done.",
      "due": "undecided"
    },
    "roadmap": [
      { "name": "AP Calculus BC Exam Booklet", "category": "I-information", "chapter": "Chapter 0", "status": "Complete", "url": "https://drive.google.com/file/d/1Zm7BzijHtGZOmttmyEjfNXPvUe-o_il7/view?usp=drive_link" },
      { "name": "AP Calculus Exam Meta Information", "category": "I-information", "chapter": "Chapter 0", "status": "Complete", "url": "https://drive.google.com/file/d/1ZQ_sPhP3ZTm9BBAlWH713yreCzF7ci-m/view?usp=drive_link" },
      { "name": "B1-Functions", "category": "B-book chapter", "chapter": "Chapter 1", "status": "Unlocked", "url": "https://drive.google.com/file/d/1JKFuYfSijODTUWMusFJS70BRhqNuvUQa/view?usp=drive_link" },
      { "name": "C1-Functions Problems", "category": "C-coursework", "chapter": "Chapter 1", "status": "Unlocked", "url": "https://drive.google.com/file/d/1srrUF6c_0cXnEdLiaD9Le05iWw7_kCXJ/view?usp=drive_link" },
      { "name": "S1-Functions Solutions", "category": "S-solution manual", "chapter": "Chapter 1", "status": "Locked", "url": "https://drive.google.com/file/d/1DPo60sEJWR7Byl70U1pOHBTQaBFw5Ey8/view?usp=drive_link" },
      { "name": "R1-Functions Review", "category": "R-Review", "chapter": "Chapter 1", "status": "Locked" },
      { "name": "T1-Functions Test", "category": "T-Test", "chapter": "Chapter 1", "status": "Locked" },
      { "name": "B2-Limits and Continuity", "category": "B-book chapter", "chapter": "Chapter 2", "status": "Optional-Reading", "url": "https://drive.google.com/file/d/1xDn8xrsDdYVlDl5l4hLWlVzWUkEe7Bs9/view?usp=drive_link" },
      { "name": "C2-Limits and Continuity Problems", "category": "C-coursework", "chapter": "Chapter 2", "status": "Optional-Reading", "url": "https://drive.google.com/file/d/1_o35NK356pUnoAIAfQZang5vgH3AMOQP/view?usp=drive_link" },
      { "name": "S2-Limits and Continuity Solutions", "category": "S-solution manual", "chapter": "Chapter 2", "status": "Locked", "url": "https://drive.google.com/file/d/17pzhOM1QGu8z-zm3YovNEe40ECpexSaF/view?usp=drive_link" },
      { "name": "R2-Functions Review", "category": "R-Review", "chapter": "Chapter 2", "status": "Locked" },
      { "name": "T2-Functions Test", "category": "T-Test", "chapter": "Chapter 2", "status": "Locked" },
      { "name": "B3-Differentiation", "category": "B-book chapter", "chapter": "Chapter 3", "status": "Optional-Reading", "url": "https://drive.google.com/file/d/1Pmtx_jKUGFLyOQhlFoYmI73UaW0AVEp7/view?usp=drive_link" },
      { "name": "C3-Differentiation Problems", "category": "C-coursework", "chapter": "Chapter 3", "status": "Optional-Reading", "url": "https://drive.google.com/file/d/19NGG8CUv7LhzRoVS6q7kx_pGaBkeHQL_/view?usp=drive_link" },
      { "name": "S3-Differentiation Solutions", "category": "S-solution manual", "chapter": "Chapter 3", "status": "Locked", "url": "https://drive.google.com/file/d/1EolTf6Fc9d4kROvX_-h_kdgXVhQCINZD/view?usp=drive_link" },
      { "name": "R3-Differentiation Review", "category": "R-Review", "chapter": "Chapter 3", "status": "Locked" },
      { "name": "T3-Differentiation Test", "category": "T-Test", "chapter": "Chapter 3", "status": "Locked" },
      { "name": "B4-Application of Differential Calculus", "category": "B-book chapter", "chapter": "Chapter 4", "status": "Locked", "url": "https://drive.google.com/file/d/176JaK2_fIDJKMu4r5lswHf55VDoHb1Yh/view?usp=drive_link" },
      { "name": "C4-Application of Differential Calculus Problems", "category": "C-coursework", "chapter": "Chapter 4", "status": "Locked", "url": "https://drive.google.com/file/d/1nEcmDBxr7c4SnXnzoqVC8xWJULMjKv1V/view?usp=drive_link" },
      { "name": "S4-Application of Differential Calculus Solutions", "category": "S-solution manual", "chapter": "Chapter 4", "status": "Locked", "url": "https://drive.google.com/file/d/1s6gS0JXb7Qkv4bcuScdMHolZpQzwZA3o/view?usp=drive_link" },
      { "name": "R4-Application of Differential Calculus Review", "category": "R-Review", "chapter": "Chapter 4", "status": "Locked" },
      { "name": "T4-Application of Differential Calculus Test", "category": "T-Test", "chapter": "Chapter 4", "status": "Locked" },
      { "name": "B5-Antidifferentiation", "category": "B-book chapter", "chapter": "Chapter 5", "status": "Locked", "url": "https://drive.google.com/file/d/1bt6G1c_qpNHzB8sk-JI2t-Vc1kaG333K/view?usp=drive_link" },
      { "name": "C5-Antidifferentiation Problems", "category": "C-coursework", "chapter": "Chapter 5", "status": "Locked", "url": "https://drive.google.com/file/d/1vNyQOAqiXgRB1yfvsxw7E5lhAxALJ8UB/view?usp=drive_link" },
      { "name": "S5-Antidifferentiation Solutions", "category": "S-solution manual", "chapter": "Chapter 5", "status": "Locked", "url": "https://drive.google.com/file/d/1dGO0xQYAWr9ial7bo62ATko0e1V9npbo/view?usp=drive_link" },
      { "name": "R5-Antidifferentiation Review", "category": "R-Review", "chapter": "Chapter 5", "status": "Locked" },
      { "name": "T5-Antidifferentiation Test", "category": "T-Test", "chapter": "Chapter 5", "status": "Locked" },
      { "name": "B6-Definite Integrals", "category": "B-book chapter", "chapter": "Chapter 6", "status": "Locked", "url": "https://drive.google.com/file/d/1zDSFHj-udXu9Qy0nrN-B8VbWRD0KmIUt/view?usp=drive_link" },
      { "name": "C6-Definite Integrals Problems", "category": "C-coursework", "chapter": "Chapter 6", "status": "Locked", "url": "https://drive.google.com/file/d/1MN9WDjoFhj29pTPRd622yPdGLKQFXsld/view?usp=drive_link" },
      { "name": "S6-Definite Integrals Solutions", "category": "S-solution manual", "chapter": "Chapter 6", "status": "Locked", "url": "https://drive.google.com/file/d/1pML1Se9S-xH4bS1TFBp3UpNSyYuqQwla/view?usp=drive_link" },
      { "name": "R6-Definite Integrals Review", "category": "R-Review", "chapter": "Chapter 6", "status": "Locked" },
      { "name": "T6-Definite Integrals Test", "category": "T-Test", "chapter": "Chapter 6", "status": "Locked" },
      { "name": "B7-Application of Integration to Geometry", "category": "B-book chapter", "chapter": "Chapter 7", "status": "Locked", "url": "https://drive.google.com/file/d/1qzq9nH9S1AKKy8maEp5tKug1sUXHBQyN/view?usp=drive_link" },
      { "name": "C7-Application of Integration to Geometry Problems", "category": "C-coursework", "chapter": "Chapter 7", "status": "Locked", "url": "https://drive.google.com/file/d/1XyXk_UTTlm4rx0PVT4fZz7VdWlNSpUcA/view?usp=drive_link" },
      { "name": "S7-Application of Integration to Geometry Solutions", "category": "S-solution manual", "chapter": "Chapter 7", "status": "Locked", "url": "https://drive.google.com/file/d/1JDNnEy-gksUoVmF-XCG1aH3_YeYqhGU5/view?usp=drive_link" },
      { "name": "R7-Application of Integration to Geometry Review", "category": "R-Review", "chapter": "Chapter 7", "status": "Locked" },
      { "name": "T7-Application of Integration to Geometry Test", "category": "T-Test", "chapter": "Chapter 7", "status": "Locked" },
      { "name": "B8-Further Applications of Integration", "category": "B-book chapter", "chapter": "Chapter 8", "status": "Locked", "url": "https://drive.google.com/file/d/1AjmoXuebty9WbTfmKgKB_EYCFP58aJWO/view?usp=drive_link" },
      { "name": "C8-Further Application of Integration Problems", "category": "C-coursework", "chapter": "Chapter 8", "status": "Locked", "url": "https://drive.google.com/file/d/1bQrM0wkcrnj0A3uIUD5NhtM5BV1CUd7i/view?usp=drive_link" },
      { "name": "S8-Further Application of Integration Solutions", "category": "S-solution manual", "chapter": "Chapter 8", "status": "Locked", "url": "https://drive.google.com/file/d/1OV_9DvjrlOeVzup-RpgobnQfMLXXn4TR/view?usp=drive_link" },
      { "name": "R8-Further Application of Integration Review", "category": "R-Review", "chapter": "Chapter 8", "status": "Locked" },
      { "name": "T8-Further Application of Integration Test", "category": "T-Test", "chapter": "Chapter 8", "status": "Locked" },
      { "name": "B9-Differential Equations", "category": "B-book chapter", "chapter": "Chapter 9", "status": "Locked", "url": "https://drive.google.com/file/d/1eW1C11UZUfhdYyEqu-yOHIh4hn_46qvA/view?usp=drive_link" },
      { "name": "C9-Differential Equations Problems", "category": "C-coursework", "chapter": "Chapter 9", "status": "Locked", "url": "https://drive.google.com/file/d/14AVNzubvCBozVWwd_UwLKAzXVqwjz0L1/view?usp=drive_link" },
      { "name": "S9-Differential Equations Solutions", "category": "S-solution manual", "chapter": "Chapter 9", "status": "Locked", "url": "https://drive.google.com/file/d/1dyBogdVu21CpfiaCyUqViZ2fVcJn01zf/view?usp=drive_link" },
      { "name": "R9-Differential Equations Review", "category": "R-Review", "chapter": "Chapter 9", "status": "Locked" },
      { "name": "T9-Differential Equations Test", "category": "T-Test", "chapter": "Chapter 9", "status": "Locked" },
      { "name": "B10-Sequences and Series", "category": "B-book chapter", "chapter": "Chapter 10", "status": "Locked", "url": "https://drive.google.com/file/d/1On07-Pxn3yhw9rqqy2UzHL_HXguwHL6H/view?usp=drive_link" },
      { "name": "C10-Sequences and Series Problems", "category": "C-coursework", "chapter": "Chapter 10", "status": "Locked", "url": "https://drive.google.com/file/d/12lbYSKyWNW1Ab100P6_wWOnWKfRVuWpm/view?usp=drive_link" },
      { "name": "S10-Sequences and Series Solutions", "category": "S-solution manual", "chapter": "Chapter 10", "status": "Locked", "url": "https://drive.google.com/file/d/1qSZ-foEm_3_UGJDIj68J5-9wvH1Ea7ga/view?usp=drive_link" },
      { "name": "R10-Sequences and Series Review", "category": "R-Review", "chapter": "Chapter 10", "status": "Locked" },
      { "name": "T10-Sequences and Series Test", "category": "T-Test", "chapter": "Chapter 10", "status": "Locked" },
      { "name": "C11-Miscellaneous Multiple Choice Questions", "category": "C-coursework", "chapter": "Chapter 11", "status": "Locked", "url": "https://drive.google.com/file/d/1LIgCn4eavP3B2Ne-gGbnKx_qr3XxT9-i/view?usp=drive_link" },
      { "name": "S11-Miscellaneous Multiple Choice Questions Solutions", "category": "S-solution manual", "chapter": "Chapter 11", "status": "Locked", "url": "https://drive.google.com/file/d/18CRylj_a4Ocnf1Yk46PQomBaI2Co84h-/view?usp=drive_link" },
      { "name": "R11-Miscellaneous Multiple Choice Questions Review", "category": "R-Review", "chapter": "Chapter 11", "status": "Locked" },
      { "name": "C12-Miscellaneous Free Response Questions", "category": "C-coursework", "chapter": "Chapter 12", "status": "Locked", "url": "https://drive.google.com/file/d/1HrGReb5uEZz-1WugOYJ8PuOrbuyRso3F/view?usp=drive_link" },
      { "name": "S12-Miscellaneous Free Response Questions Solutions", "category": "S-solution manual", "chapter": "Chapter 12", "status": "Locked", "url": "https://drive.google.com/file/d/1rBXVa-9OfhdPeUCI7d_FHJKNRn2j4nrM/view?usp=drive_link" },
      { "name": "R12-Miscellaneous Free Response Questions Review", "category": "R-Review", "chapter": "Chapter 12", "status": "Locked" },
      { "name": "M1-Full Mock Test 1", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1tAhprt5xldGpONJlyAbeRicCrrgkAZdM/view?usp=drive_link" },
      { "name": "M1S-Full Mock Test 1 Solution", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1RBhkIDr8DKTJzRmGeEc9BrUTEv1UiTSy/view?usp=drive_link" },
      { "name": "M1R-Full Mock Test 1 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M2-Full Mock Test 2", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1U8c-vo8NzxvI_0x_Aw2LQQy3WXybmC6i/view?usp=drive_link" },
      { "name": "M2S-Full Mock Test 2 Solution", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1S_Bb_j6w2kPY4__UpEchcJkl9vkznldS/view?usp=drive_link" },
      { "name": "M2R-Full Mock Test 2 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M3-Full Mock Test 3", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1gL7bJ4yffCR2EZ2wNOe3TnEJo_MjiHum/view?usp=drive_link" },
      { "name": "M3S-Full Mock Test 3 Solution", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1IFWIPap_A-xm6LGGtP3QqT_bV69nHk7_/view?usp=drive_link" },
      { "name": "M3R-Full Mock Test 3 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M4-FRQ Mock 4", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1IDfZvY8lVcCUwqbYCjTu32cVqdDXVaf4/view?usp=drive_link" },
      { "name": "M4S-FRQ Mock 4 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1PVw15uOPBzefCLjEZXZ5f_OqVxFOXU2W/view?usp=drive_link" },
      { "name": "M4R-FRQ Mock 4 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M5-FRQ Mock 5", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/13um9F8xTM-NGdsNghkEvv3_KrspUjLHk/view?usp=drive_link" },
      { "name": "M5S-FRQ Mock 5 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1HZi_LvVrumTfe3VKaQelGssmyFwfiiuC/view?usp=drive_link" },
      { "name": "M5R-FRQ Mock 5 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M6-FRQ Mock 6", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1vQeyfNHgOMp8quhft1mTcPq4XSlb52RD/view?usp=drive_link" },
      { "name": "M6S-FRQ Mock 6 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/15DuEPBbg04fDeS8PUMaCRsFHfC1EzEfc/view?usp=drive_link" },
      { "name": "M6R-FRQ Mock 6 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M7-FRQ Mock 7", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1_LkWfuAsZUOYvANxiVYdXIa7bULO7Yzh/view?usp=drive_link" },
      { "name": "M7S-FRQ Mock 7 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1vj-VgWY-wT00RkdY4wUbHPh7XJ_MtyNk/view?usp=drive_link" },
      { "name": "M8R-FRQ Mock 7 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M8-FRQ Mock 8", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1KqvLYIis_8feMVS1zDixS6PPZjBxtXHd/view?usp=drive_link" },
      { "name": "M8S-FRQ Mock 8 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1eG9Ksj6Af8t6PGX7R_T3knVLgsCg8e38/view?usp=drive_link" },
      { "name": "M8R-FRQ Mock 8 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M9-FRQ Mock 9", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1E1rDrUFeh2311Gzg3ln3eR5Bsu1yJZeQ/view?usp=drive_link" },
      { "name": "M9S-FRQ Mock 9 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1hh-sZH8uxDsR0V8O3nhjJ_BkFvfuQ3Ap/view?usp=drive_link" },
      { "name": "M9R-FRQ Mock 9 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" },
      { "name": "M10-FRQ Mock 10", "category": "M-Mock", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1AZPOd1iaPTA8JJJmlooee7Ym1D9Jq79H/view?usp=drive_link" },
      { "name": "M10S-FRQ Mock 10 Solutions", "category": "S-solution manual", "chapter": "Chapter M", "status": "Locked", "url": "https://drive.google.com/file/d/1V36m1RowaKnVLvcEb7dxJEFWGpsp3DFJ/view?usp=drive_link" },
      { "name": "M10R-FRQ Mock 10 Review", "category": "R-Review", "chapter": "Chapter M", "status": "Locked" }
    ]
  },
  {
    "username": "kyjv9981",
    "password": "password",
    "name": "Yong Joon Kim",
    "portal": {
      "notionUrl": "d",
      "notionAvailable": false
    },
    "rightNow": {
      "state": "your-move",
      "chapter": "Chapter 6",
      "unit": "B",
      "instruction": "Read through the chapter and actively work through the examples as you go — don't just read past them. Use whatever helps you actually close the gaps. Message us once you're done.",
      "due": "Friday"
    },
    "feedback": [
      {
        "date": "Jul 22",
        "chapter": "Chapter 5",
        "unit": "S",
        "content": "Nice improvement on related rates since last time. Keep working through the 발상노트 for the two problems you missed — both were domain-restriction oversights, same pattern as Chapter 4."
      },
      {
        "date": "Jul 12",
        "chapter": "Chapter 4",
        "unit": "C",
        "content": "Solid effort. Most of what you missed came down to forgetting to check the domain before finalizing an answer — worth a quick habit check before submitting next time."
      }
    ],
    "cheatSheet": [
      {
        "topic": "Domain Restrictions",
        "source": "4C-14, 5S-9",
        "pattern": "Shows up twice so far — the method is right both times, the answer just isn't checked against the original expression's domain afterward. Before finalizing, ask: does this value actually work back in the un-simplified expression, e.g. is $x=-2$ still valid if the original required $x > 0$?"
      },
      {
        "topic": "Related Rates Setup",
        "source": "5C-6",
        "pattern": "Going well — keep setting up straight from the diagram: $\\dfrac{dV}{dt} = \\dfrac{dV}{dr} \\cdot \\dfrac{dr}{dt}$ rather than re-deriving the volume formula each time. Faster and less room for a sign slip."
      }
    ]
  }
];

// Teachers are a separate list from STUDENTS — same username/password
// shape, but they log into a different dashboard (teacher.html) with
// its own layout instead of the student portal pages. Kept minimal
// for now; the actual dashboard content/structure is still TBD.
const TEACHERS = [
  {
    "username": "teacher",
    "password": "password",
    "name": "Zenith Teacher"
  }
];
