/**
 * Zenith — Teacher dashboard data writer
 * -----------------------------------------
 * Standalone Apps Script Web App (a separate deployment from both
 * submissions-compiler.gs and submission-status-updater.gs) that backs
 * every "write" control on teacher-student.html: unlocking a roadmap
 * item, adding a feedback entry, adding a cheat sheet entry, updating
 * a course's Right Now task, and logging a metrics data point. It is
 * the one thing in this repo that writes to js/data.js — nothing else
 * does; that file has always been hand-edited (or regenerated by the
 * separate, currently-broken zenith-cli tool) until now.
 *
 * Like submission-status-updater.gs, this endpoint is deliberately
 * narrow rather than deployment-access-restricted: SUBMISSION_
 * STATUS_UPDATE_URL's sibling here, TEACHER_DATA_WRITE_URL (js/data.js),
 * is visible to anyone who views page source — same as everything
 * else in that file (see its "NOT SECURE" header comment). What
 * actually bounds the risk is that every action below is a single,
 * specific, whitelisted mutation (flip one roadmap item's status,
 * append one feedback/cheat-sheet/metrics entry, replace one course's
 * rightNow) — never an arbitrary field write, never a delete, never
 * touching TEACHERS/PARENTS or any student's login credentials.
 *
 * This file is a reference copy for version history — the version
 * that actually runs lives inside its own Apps Script project (step 2
 * below), not here. Copy it in by hand; nothing auto-syncs.
 *
 * ---------------------------------------------------------------
 * THE "js/data.js IS NOT JSON" PROBLEM
 * ---------------------------------------------------------------
 * js/data.js is a hand-authored JavaScript file (`const STUDENTS =
 * [...]`), not a .json file, so it can't be read with a plain
 * JSON.parse the way submissions-log.json is in the other two
 * scripts. findConstArraySpan_/readConstArray_/spliceConstArray_
 * below solve this by locating exactly the `const STUDENTS = [ ... ]`
 * span in the raw file text (a bracket-depth scanner that also
 * tracks string-literal boundaries, so it finds the true matching
 * close, not just the first stray "]"), evaluating only that span
 * (safe here — this is trusted first-party code reading its own
 * repo's data, not arbitrary user input), mutating the resulting
 * plain object in memory, then re-serializing with JSON.stringify and
 * splicing it back into the original file text in place of the old
 * span. Everything outside that span — the header comment, the other
 * consts (CALENDAR_URL, SUBMISSION_FORM_URL, the field-shape docs),
 * TEACHERS, PARENTS — is left untouched byte-for-byte.
 *
 * Caveat worth knowing: any hand-written comment *inside* a STUDENTS
 * array entry (there are none as of this writing — see the field-shape
 * docs, which all live above the array) would be lost the next time
 * this script writes, since JSON.stringify can't preserve comments.
 * This is the same tradeoff js/data.js's own header comment already
 * describes for zenith-cli ("hand edits survive until the next
 * `zenith` command writes to it").
 *
 * ---------------------------------------------------------------
 * ONE-TIME SETUP
 * ---------------------------------------------------------------
 * 1. script.google.com -> New project. Paste this whole file in,
 *    replacing whatever is in Code.gs. (Its own standalone project —
 *    not the same one as submission-status-updater.gs or the
 *    Form-bound submissions-compiler.gs.)
 *
 * 2. Project Settings (gear icon) -> Script Properties -> add:
 *      GITHUB_TOKEN   Fine-grained PAT scoped to ONLY this repo, with
 *                     "Contents: Read and write" permission.
 *      GITHUB_OWNER   the-zenithway
 *      GITHUB_REPO    the-zenithway.github.io
 *      GITHUB_BRANCH  main
 *      DATA_PATH      js/data.js
 *
 * 3. Deploy -> New deployment -> "Web app".
 *      Execute as:      Me
 *      Who has access:  Anyone
 *    Copy the resulting /exec URL.
 *
 * 4. Paste that URL into TEACHER_DATA_WRITE_URL in js/data.js and
 *    commit. Every write control on teacher-student.html starts
 *    working as soon as that's live.
 *
 * 5. Try one action for real (e.g. add a cheat sheet entry to a test
 *    student) and check main on GitHub for a commit updating
 *    js/data.js with exactly that one change and nothing else.
 *
 * ---------------------------------------------------------------
 * WHAT COUNTS AS "DONE" HERE
 * ---------------------------------------------------------------
 * Untested against a real deployment — same caveat as
 * submission-status-updater.gs; I can't run Apps Script myself. The
 * GitHub Contents API read/PUT/retry pattern is copied directly from
 * the other two scripts, which ARE confirmed working. The new parts —
 * findConstArraySpan_ and the action handlers — are the pieces to
 * watch on the first real run. If step 5 throws or produces an
 * unexpected diff, send the exact error text or diff.
 */

function doPost(e) {
  try {
    var body = JSON.parse(e.postData.contents);
    var action = body.action;
    var payload = body.payload || {};
    var handler = ACTIONS[action];
    if (!handler) return jsonResponse_({ ok: false, error: "Unknown action: " + action });

    var props = PropertiesService.getScriptProperties();
    var token = props.getProperty("GITHUB_TOKEN");
    var owner = props.getProperty("GITHUB_OWNER");
    var repo = props.getProperty("GITHUB_REPO");
    var branch = props.getProperty("GITHUB_BRANCH") || "main";
    var path = props.getProperty("DATA_PATH") || "js/data.js";

    if (!token || !owner || !repo) {
      throw new Error("Missing GITHUB_TOKEN/GITHUB_OWNER/GITHUB_REPO script property — see setup steps at the top of this file.");
    }

    applyActionAndCommit_(owner, repo, branch, path, token, action, handler, payload);
    return jsonResponse_({ ok: true });
  } catch (err) {
    return jsonResponse_({ ok: false, error: String(err) });
  }
}

function jsonResponse_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

// ---------------------------------------------------------------
// Action handlers — each takes (students, payload), mutates the
// `students` array in place, and throws a descriptive error on any
// missing/invalid input. Kept deliberately narrow: one action, one
// specific mutation, nothing generic/arbitrary.
// ---------------------------------------------------------------

var ROADMAP_STATUSES_ = ["Locked", "Unlocked", "Complete", "Review", "Optional-Reading"];
var METRIC_ARRAY_TYPES_ = ["topicMastery", "chapterScores", "motivation", "mockScores", "timeToCompletion"];
var AP_SCORE_FIELDS_ = ["apPredictedScore", "apFinalScore"];

function findCourse_(students, username, courseId) {
  var student = students.find(function (s) { return s.username === username; });
  if (!student) throw new Error("No student with username " + username);
  var course = (student.courses || []).find(function (c) { return c.id === courseId; });
  if (!course) throw new Error("Student " + username + " is not enrolled in course " + courseId);
  return course;
}

var ACTIONS = {
  updateRoadmapStatus: function (students, payload) {
    var course = findCourse_(students, payload.username, payload.courseId);
    if (ROADMAP_STATUSES_.indexOf(payload.status) === -1) {
      throw new Error("Invalid status: " + payload.status);
    }
    var item = (course.roadmap || []).find(function (it) {
      return it.chapter === payload.chapter && it.name === payload.name;
    });
    if (!item) throw new Error("No roadmap item matching chapter \"" + payload.chapter + "\" / name \"" + payload.name + "\"");
    item.status = payload.status;
  },

  addFeedback: function (students, payload) {
    var course = findCourse_(students, payload.username, payload.courseId);
    if (!payload.date || !payload.chapter || !payload.unit || !payload.content) {
      throw new Error("addFeedback requires date, chapter, unit, and content");
    }
    if (!course.feedback) course.feedback = [];
    course.feedback.unshift({
      date: payload.date,
      chapter: payload.chapter,
      unit: payload.unit,
      content: payload.content
    });
  },

  addCheatSheetEntry: function (students, payload) {
    var course = findCourse_(students, payload.username, payload.courseId);
    if (!payload.topic || !payload.source || !payload.pattern) {
      throw new Error("addCheatSheetEntry requires topic, source, and pattern");
    }
    if (!course.cheatSheet) course.cheatSheet = [];
    course.cheatSheet.push({
      topic: payload.topic,
      source: payload.source,
      pattern: payload.pattern
    });
  },

  updateRightNow: function (students, payload) {
    var course = findCourse_(students, payload.username, payload.courseId);
    var rightNow = payload.rightNow;
    if (!rightNow || (rightNow.state !== "your-move" && rightNow.state !== "waiting")) {
      throw new Error("updateRightNow requires rightNow.state to be \"your-move\" or \"waiting\"");
    }
    if (!rightNow.chapter || !rightNow.unit) {
      throw new Error("updateRightNow requires rightNow.chapter and rightNow.unit");
    }
    if (rightNow.state === "your-move" && !rightNow.instruction) {
      throw new Error("updateRightNow requires rightNow.instruction when state is \"your-move\"");
    }
    if (rightNow.state === "waiting" && !rightNow.note) {
      throw new Error("updateRightNow requires rightNow.note when state is \"waiting\"");
    }
    course.rightNow = rightNow;
    if (payload.rightNowNext) course.rightNowNext = payload.rightNowNext;
    else delete course.rightNowNext;
  },

  addMetricEntry: function (students, payload) {
    var course = findCourse_(students, payload.username, payload.courseId);
    if (METRIC_ARRAY_TYPES_.indexOf(payload.metricType) === -1) {
      throw new Error("Invalid metricType: " + payload.metricType);
    }
    if (!payload.entry) throw new Error("addMetricEntry requires an entry");
    if (!course.metrics) course.metrics = {};
    if (!course.metrics[payload.metricType]) course.metrics[payload.metricType] = [];
    course.metrics[payload.metricType].push(payload.entry);
  },

  setApScore: function (students, payload) {
    var course = findCourse_(students, payload.username, payload.courseId);
    if (AP_SCORE_FIELDS_.indexOf(payload.field) === -1) {
      throw new Error("Invalid field: " + payload.field);
    }
    if (!payload.value) throw new Error("setApScore requires a value");
    if (!course.metrics) course.metrics = {};
    course.metrics[payload.field] = payload.value;
  }
};

// ---------------------------------------------------------------
// js/data.js text <-> real object bridge
// ---------------------------------------------------------------

// Finds `const <constName> = [ ... ]` in raw source text and returns
// the exact character span of the array literal (including its own
// brackets), by walking the text tracking [ { } ] depth and skipping
// over string-literal contents (so a "]" inside a URL or feedback
// string doesn't get mistaken for the end of the array).
function findConstArraySpan_(source, constName) {
  var marker = "const " + constName + " = [";
  var markerStart = source.indexOf(marker);
  if (markerStart === -1) throw new Error("Could not find \"" + marker + "\" in the file");

  var literalStart = markerStart + marker.length - 1; // index of the "["
  var depth = 0;
  var inString = false;
  var stringChar = "";
  var i = literalStart;

  for (; i < source.length; i++) {
    var ch = source.charAt(i);
    var prevCh = i > 0 ? source.charAt(i - 1) : "";

    if (inString) {
      if (ch === stringChar && prevCh !== "\\") inString = false;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      inString = true;
      stringChar = ch;
      continue;
    }
    if (ch === "[" || ch === "{") {
      depth++;
    } else if (ch === "]" || ch === "}") {
      depth--;
      if (depth === 0) { i++; break; } // i now points just past the matching "]"
    }
  }

  if (depth !== 0) throw new Error("Could not find the matching closing bracket for " + constName);
  return { literalStart: literalStart, literalEnd: i };
}

// Reads `const <constName> = [...]`'s current value as a real JS
// array. eval is safe here specifically because this is trusted
// first-party code reading its own repo's data file, not arbitrary
// user/network input.
function readConstArray_(source, constName) {
  var span = findConstArraySpan_(source, constName);
  var literalText = source.slice(span.literalStart, span.literalEnd);
  return eval("(" + literalText + ")");
}

// Replaces `const <constName> = [...]`'s array literal with
// JSON.stringify(newValue) — everything else in the file (comments,
// other consts) is left untouched.
function spliceConstArray_(source, constName, newValue) {
  var span = findConstArraySpan_(source, constName);
  var newLiteral = JSON.stringify(newValue, null, 2);
  return source.slice(0, span.literalStart) + newLiteral + source.slice(span.literalEnd);
}

// ---------------------------------------------------------------
// GitHub Contents API read/mutate/write, same GET -> mutate -> PUT
// (+409 retry) pattern as commitNewEntry_ in submissions-compiler.gs
// and markComplete_ in submission-status-updater.gs.
// ---------------------------------------------------------------
function applyActionAndCommit_(owner, repo, branch, path, token, actionName, handler, payload, attempt) {
  attempt = attempt || 1;
  var apiUrl = "https://api.github.com/repos/" + owner + "/" + repo + "/contents/" + path + "?ref=" + branch;
  var headers = { Authorization: "token " + token, Accept: "application/vnd.github+json" };

  var getResp = UrlFetchApp.fetch(apiUrl, { headers: headers, muteHttpExceptions: true });
  if (getResp.getResponseCode() !== 200) {
    throw new Error("Could not read " + path + " on branch " + branch + " (HTTP " + getResp.getResponseCode() + "): " + getResp.getContentText());
  }
  var file = JSON.parse(getResp.getContentText());
  var source = Utilities.newBlob(Utilities.base64Decode(file.content)).getDataAsString();

  var students = readConstArray_(source, "STUDENTS");
  handler(students, payload); // mutates `students` in place; throws on invalid payload
  var newSource = spliceConstArray_(source, "STUDENTS", students);

  var newContent = Utilities.base64Encode(newSource, Utilities.Charset.UTF_8);
  var putResp = UrlFetchApp.fetch(
    "https://api.github.com/repos/" + owner + "/" + repo + "/contents/" + path,
    {
      method: "put",
      headers: headers,
      contentType: "application/json",
      muteHttpExceptions: true,
      payload: JSON.stringify({
        message: "Teacher dashboard: " + actionName + " for " + payload.username + (payload.courseId ? " / " + payload.courseId : ""),
        content: newContent,
        sha: file.sha,
        branch: branch
      })
    }
  );

  if (putResp.getResponseCode() === 409 && attempt < 3) {
    Utilities.sleep(500 * attempt);
    applyActionAndCommit_(owner, repo, branch, path, token, actionName, handler, payload, attempt + 1);
    return;
  }
  if (putResp.getResponseCode() >= 300) {
    throw new Error("Could not write " + path + " (HTTP " + putResp.getResponseCode() + "): " + putResp.getContentText());
  }
}
